### ISSUE TITLE
ranger-sixel image previews are broken

### ISSUE THREAD

**Issue by Martinits** [microo8/alacritty-sixel#10]
Hello, I'm using archlinux, sway, alacritty-sixel (0.12.0-dev (53110c6e)) and ranger-sixel both installed from AUR. It shows broken previews like in the picture and flickers sometimes. But after refreshing the screen like screenshoting or switching to another workspace then back, the preview goes back to normal. Maybe it's a problem with wayland because It's good on X11. Also, when using another machine(X11) to ssh into the current one(Sway), all are good. I also tried `lsix` on sway, which works stably. Is this a known problem or how can I fix that? The picture is taken with my phone because when screenshoting the preview is good like what I just said.

![grimshot-22-10-18-13-38-39-705605628](https://user-images.githubusercontent.com/48900241/196340165-ddc7f829-83fa-45a0-bd0b-a6826602982c.png)

**Comment by kumattau** [comment]
This sixel implementation is old version of https://github.com/alacritty/alacritty/pull/4763 .
Now, original author @ayosec updates sixel implementation based on the current latest master.
Maybe good for you to try the updated implementation.

**Comment by lelgenio** [comment]
@Martinits, As a practical solution you should probably use the `ranger-sixel-git` package from the AUR, which has a updated version of the PR, this issue was recently fixed there.

**Comment by Martinits** [comment]
Thanks. It's OK now.
